### ISSUE TITLE
[1.18.2-Forge] Crashes when loaded on servers.

### ISSUE THREAD

**Issue by Gbergz** [Kitoglav/Amethyst-Tools-Mod#1]
Title ^

Forge: 40.0.45
Mod Version: 1.18.2-1.4.0 | https://www.curseforge.com/minecraft/mc-mods/amethyst-tools-mod/files/3744989
Crash-Report: https://gist.github.com/Gbergz/7326cf75c09cc6817fce0e72201e8f74

**-** Gbergz

**Comment by Kitoglav** [comment]
I'm sorry. I'll fix it today. Wait for 1.4.1 update.

**Comment by Kitoglav** [comment]
problem resolved. just update mod. good luck <3
