### ISSUE TITLE
recipe problem

### ISSUE THREAD

**Issue by XFro5ty** [Kitoglav/Amethyst-Tools-Mod#2]
[prob.txt](https://github.com/Kitoglav/Amethyst-Tools-Mod/files/8486734/prob.txt)

**Comment by Kitoglav** [comment]
Update to the latest version 1.4.1. VanillaExcavators/VanillaHammers/Lumberjack are no longer supported

**Comment by Kitoglav** [comment]
1.4.1 works on all 1.18.x versions
