### ISSUE TITLE
[1.18.2] Amethyst Arrow Crash

### ISSUE THREAD

**Issue by Gbergz** [Kitoglav/Amethyst-Tools-Mod#3]
Title^

### Versions
**Minecraft**: 1.18.2
**Forge**: 40.0.52
**Amethyst**: 1.4.1 | https://www.curseforge.com/minecraft/mc-mods/amethyst-tools-mod/files/3751647

### Crash-Report:
https://gist.github.com/Gbergz/0aae8fdfcbf116da919ce291e3dac066

**-** Gbergz

**Comment by Kitoglav** [comment]
I will update mod in 20 mins, I'm sorry for this bug

**Comment by Gbergz** [comment]
Np. Looking forward to it! :)

**Comment by Kitoglav** [comment]
Curseforge is processing mod. It will be available in few minutes. Thanks you for waiting
