### ISSUE TITLE
found a error in minecraft 1.19 

### ISSUE THREAD

**Issue by ghost** [Kitoglav/Amethyst-Tools-Mod#7]
hello, i found an issue about this mod recently, i putted and it pop me an error that says this: 
![image](https://user-images.githubusercontent.com/109100627/178322905-b2643818-3bf9-4692-956c-a16de2bb1e8d.png)
how could i fix it ?

**Comment by Kitoglav** [comment]
Sorry for long waiting. Send me your crashlog

**Comment by Kitoglav** [comment]
Fixed in latest version.
